problemsToReport:
  - DEPRECATED_COLLECTION_USED
  - COLLECTION_IS_EMPTY_REIMPLEMENTED
  - STRING_IS_EMPTY_REIMPLEMENTED
  - INVALID_AUTHOR_TAG
  - COMMENTED_OUT_CODE
  - INCONSISTENT_COMMENT_LANGUAGE
  - INVALID_COMMENT_LANGUAGE
  - JAVADOC_STUB_DESCRIPTION
  - JAVADOC_STUB_PARAMETER_TAG
  - JAVADOC_STUB_RETURN_TAG
  - JAVADOC_STUB_THROWS_TAG
  - JAVADOC_MISSING_PARAMETER_TAG
  - JAVADOC_UNKNOWN_PARAMETER_TAG
  - UNUSED_DIAMOND_OPERATOR
  - EXPLICITLY_EXTENDS_OBJECT
  - FOR_WITH_MULTIPLE_VARIABLES
  - REDUNDANT_DEFAULT_CONSTRUCTOR
  - REDUNDANT_IF_FOR_BOOLEAN
  - REDUNDANT_MODIFIER
  - REDUNDANT_VOID_RETURN
  - REDUNDANT_SELF_ASSIGNMENT
  - REDUNDANT_VARIABLE
  - UNUSED_IMPORT
  - PRIMITIVE_WRAPPER_INSTANTIATION
  - ASSERT
  - EXCEPTION_PRINT_STACK_TRACE
  - CUSTOM_EXCEPTION_INHERITS_RUNTIME_EXCEPTION
  - CUSTOM_EXCEPTION_INHERITS_ERROR
  - EMPTY_CATCH
  - EXCEPTION_CAUGHT_IN_SURROUNDING_BLOCK
  - RUNTIME_EXCEPTION_CAUGHT
  - OBJECTS_COMPARED_VIA_TO_STRING
  - FIELD_SHOULD_BE_CONSTANT
  - DUPLICATE_CODE
  - REASSIGNED_PARAMETER
  - DOUBLE_BRACE_INITIALIZATION
  - FOR_CAN_BE_FOREACH
  - OVERRIDE_ANNOTATION_MISSING
  - SYSTEM_SPECIFIC_LINE_BREAK
  - BOOLEAN_GETTER_NOT_CALLED_IS
  - MEANINGLESS_CONSTANT_NAME
  - CONFUSING_IDENTIFIER
  - SINGLE_LETTER_LOCAL_NAME
  - IDENTIFIER_IS_ABBREVIATED_TYPE
  - CONCRETE_COLLECTION_AS_FIELD_OR_RETURN_VALUE
  - LEAKED_COLLECTION_ASSIGN
  - LEAKED_COLLECTION_RETURN
  - METHOD_USES_PLACEHOLDER_IMPLEMENTATION
  - UTILITY_CLASS_NOT_FINAL
  - UTILITY_CLASS_INVALID_CONSTRUCTOR
  - DEFAULT_PACKAGE_USED
  - EMPTY_BLOCK
  - UNUSED_CODE_ELEMENT
  - REPEATED_MATH_OPERATION
  - STATIC_FIELD_SHOULD_BE_INSTANCE
  - FIELD_SHOULD_BE_FINAL
  - STRING_COMPARE_BY_REFERENCE
  - REDUNDANT_NEGATION
  - JAVADOC_UNEXPECTED_TAG
  - UNMERGED_ELSE_IF
  - EXCEPTION_WITHOUT_MESSAGE
  - DO_NOT_USE_RAW_TYPES
  - DO_NOT_HAVE_CONSTANTS_CLASS
  - EMPTY_INTERFACE
  - UI_INPUT_SEPARATION
  - UI_OUTPUT_SEPARATION
  - USE_OPERATOR_ASSIGNMENT
  - DO_NOT_USE_SYSTEM_EXIT
  - AVOID_INNER_CLASSES
  - USE_STRING_FORMATTED
  - OPTIONAL_TRI_STATE
  - AVOID_LABELS
  - AVOID_SHADOWING
  - SUPPRESS_WARNINGS_USED
  - COMPLEX_REGEX
  - SCANNER_MUST_BE_CLOSED
  - EQUALS_HASHCODE_COMPARABLE_CONTRACT
  - UNCHECKED_TYPE_CAST
  - MUTABLE_ENUM
  - JAVADOC_UNDOCUMENTED_THROWS
  - USE_FORMAT_STRING
  - SHOULD_BE_ENUM_ATTRIBUTE
  - CLOSED_SET_OF_VALUES
  - TYPE_HAS_DESCRIPTIVE_NAME
  - LOCAL_VARIABLE_SHOULD_BE_CONSTANT
  - USE_ENUM_COLLECTION
  - INSTANCEOF
  - INSTANCEOF_EMULATION
  - COMPARE_CHAR_VALUE
  - REDUNDANT_CATCH
  - IDENTIFIER_CONTAINS_TYPE_NAME
  - USE_GUARD_CLAUSES
  - SIMILAR_IDENTIFIER
  - PACKAGE_NAMING_CONVENTION
  - IDENTIFIER_REDUNDANT_NUMBER_SUFFIX
  - REDUNDANT_UNINITIALIZED_VARIABLE
  - IMPORT_TYPES
  - USE_DIFFERENT_VISIBILITY
  - USE_DIFFERENT_VISIBILITY_PEDANTIC
  - REDUNDANT_BOOLEAN_EQUAL
  - AVOID_RECOMPILING_REGEX
  - MERGE_NESTED_IF
  - COMPARE_TO_ZERO
  - EQUALS_USING_HASHCODE
  - EQUALS_UNSAFE_CAST
  - EQUALS_INCOMPATIBLE_TYPE
  - INCONSISTENT_HASH_CODE
  - UNDEFINED_EQUALS
  - EQUALS_BROKEN_FOR_NULL
  - NON_OVERRIDING_EQUALS
  - ARRAYS_HASHCODE
  - EQUALS_REFERENCE
  - ARRAY_AS_KEY_OF_SET_OR_MAP
  - MULTIPLE_INLINE_STATEMENTS
  - UNNECESSARY_BOXING
  - COMMON_REIMPLEMENTATION_ARRAY_COPY
  - COMMON_REIMPLEMENTATION_STRING_REPEAT
  - ABSTRACT_CLASS_WITHOUT_ABSTRACT_METHOD
  - SHOULD_BE_INTERFACE
  - COMPOSITION_OVER_INHERITANCE
  - USE_ENTRY_SET
  - CHAR_RANGE
  - UNUSED_CODE_ELEMENT_PRIVATE
  - COMMON_REIMPLEMENTATION_MAX_MIN
  - FOR_LOOP_CAN_BE_INVOCATION
  - COMMON_REIMPLEMENTATION_ARRAYS_FILL
  - EXCEPTION_SHOULD_NEVER_BE_CAUGHT
  - USE_DIFFERENT_VISIBILITY_PUBLIC_FIELD
  - MULTI_THREADING
  - BINARY_OPERATOR_ON_BOOLEAN
  - TODO_COMMENT
  - USE_ENUM_VALUES
  - COMMON_REIMPLEMENTATION_SUBLIST
  - REDUNDANT_MODIFIER_VISIBILITY_ENUM_CONSTRUCTOR
  - TOO_MANY_EXCEPTIONS
  - TOO_FEW_PACKAGES
  - TRY_CATCH_COMPLEXITY
  - AVOID_STATIC_BLOCKS
  - AVOID_STRING_CONCAT
  - UNNECESSARY_COMMENT
  - OBJECT_DATATYPE
  - COMMON_REIMPLEMENTATION_SQRT
  - COMMON_REIMPLEMENTATION_HYPOT
  - CONSTANT_NAME_CONTAINS_VALUE
  - MAGIC_LITERAL
  - IMPLEMENT_COMPARABLE
  - SIMPLIFY_ARRAYS_FILL
  - COMMON_REIMPLEMENTATION_ITERABLE_DUPLICATES
  - COLLECTIONS_N_COPIES
  - REDUNDANT_ELSE
  - SEQUENTIAL_ADD_ALL
  - USE_MODULO_OPERATOR
  - NUMBER_FORMAT_EXCEPTION_IGNORED
  - REDUNDANT_ASSIGNMENT
  - LOOP_SHOULD_BE_DO_WHILE
  - LOOP_SHOULD_BE_FOR
  - METHOD_SHOULD_BE_STATIC
  - METHOD_SHOULD_BE_STATIC_NOT_PUBLIC
  - IS_LETTER_OR_DIGIT
  - LOOP_SHOULD_BE_WHILE
  - USE_ARRAYS_COPY_OF
  - SIMPLIFY_STRING_SUBSTRING
  - DUPLICATE_CATCH_BLOCK
  - DUPLICATE_IF_BLOCK
  - TRY_BLOCK_SIZE
